### PR TITLE
Nick - Connect Restaurants frontend to backend

### PR DESCRIPTION
**Pull request by nickzahlis**
Nick - Added Index and Details pages + tests
Kane - Added the Table, Create, and Edit pages + tests

### CODE REVIEW

**Comment by wq12li** [comment]
Something seems a little bizarre with the change count.

**Comment by nickzahlis** [comment]
Yeah I'm not quite sure what the issue is. I'm changing this to a draft PR until I find out what happened

**Comment by nickzahlis** [comment]
I've fixed the problem with the change count and all of the tests are passing, so I'm marking this PR as ready for review

**Review by wq12li — APPROVED** [review]
Passes all tests and functional on both localhost and QA. Approving.

**Review by nagpalishaan — APPROVED** [review]

**Pull request merged**
